/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package railwayreservation;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
//import java.sql.Connection;
//import java.sql.DriverManager;
//import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
/**
 *
 * @author apple
 */
public class train extends javax.swing.JFrame {

    /**
     * Creates new form train
     */
    public train() {
        initComponents();
        connect();
       setSize(540, 460);
    }
    Connection conn;
    PreparedStatement pst;
    public void connect()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/railway reservation", "root", "");
            
        } 
        catch (ClassNotFoundException ex) {
            Logger.getLogger(passenger.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (SQLException ex) {
            Logger.getLogger(passenger.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        tnum = new javax.swing.JTextField();
        tname = new javax.swing.JTextField();
        seats = new javax.swing.JTextField();
        source = new javax.swing.JComboBox<>();
        destination = new javax.swing.JComboBox<>();
        addtrain = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        jLabel1.setText("Train number");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        jLabel2.setText("Train Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        jLabel3.setText("Total Seats");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        jLabel4.setText("Source");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        jLabel5.setText("Destination");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Malayalam MN", 1, 36)); // NOI18N
        jLabel6.setText("TRAIN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, -1));

        jToggleButton1.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jToggleButton1.setText("HOME");
        jToggleButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        getContentPane().add(tnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 170, 40));
        getContentPane().add(tname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 170, 40));
        getContentPane().add(seats, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 170, 40));

        source.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        source.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banglore", "Bandipur", "Coorg", "Hampi", "Mysore", "Shivanasamudra", "Gokarna", "Sagar", "Dandeli", "Udupi", "Chickmagalur", "Karwar", "Goa", "Shimla", "Delhi" }));
        source.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceActionPerformed(evt);
            }
        });
        getContentPane().add(source, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        destination.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        destination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banglore", "Bandipur", "Coorg", "Hampi", "Mysore", "Shivanasamudra", "Gokarna", "Sagar", "Dandeli", "Udupi", "Chickmagalur", "Karwar", "Goa", "Shimla", "Delhi" }));
        destination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationActionPerformed(evt);
            }
        });
        getContentPane().add(destination, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        addtrain.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        addtrain.setText("Add Train");
        addtrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtrainActionPerformed(evt);
            }
        });
        getContentPane().add(addtrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 150, -1));

        jButton1.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 100, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("/Users/apple/Desktop/projects/DBMS/railwayreservation/images/unnamed.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void sourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_sourceActionPerformed

    private void addtrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtrainActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/railway reservation", "root", "");
            String sql="insert into Train (T_num,T_name,Total_seats,source,destination) values(?,?,?,?,?)";
            PreparedStatement pst=conn.prepareStatement(sql);
            pst.setInt(1,Integer.parseInt(tnum.getText()));
            pst.setString(2, tname.getText());
            pst.setInt(3,Integer.parseInt(seats.getText()));
            String src= source.getSelectedItem().toString();
            pst.setString(4, src);
            String dest= destination.getSelectedItem().toString();
            pst.setString(5, dest);
            
            pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "insersion successful");
            conn.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(passenger.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(train.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
//        try {
//            Class.forName("com.mysql.jdbc.Driver");
//            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/railway reservation", "root", "");
//            String sql= "delete from passenger where P_id=?";
//            PreparedStatement pst=conn.prepareStatement(sql);
//            pst.setString(1, pid.getText());
//        
//            int n= pst.executeUpdate();
//            System.out.println(n);
//            if(n==1)
//            {
//                JOptionPane.showMessageDialog(null, "Record delected");
//            }
//            else
//            {
//                JOptionPane.showMessageDialog(null, "No Record found");
//            }
//        } 
//        catch (ClassNotFoundException ex) {
//            Logger.getLogger(passenger.class.getName()).log(Level.SEVERE, null, ex);
//        } 
//        catch (SQLException ex) {
//            Logger.getLogger(passenger.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_addtrainActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tnum.setText("");
        tname.setText("");
        seats.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        new main().setVisible(true);
        dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void destinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationActionPerformed
        // TODO add your handling code here:
        String selectedValue = destination.getSelectedItem().toString();
        
    }//GEN-LAST:event_destinationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(train.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(train.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(train.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(train.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new train().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addtrain;
    private javax.swing.JComboBox<String> destination;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField seats;
    private javax.swing.JComboBox<String> source;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField tnum;
    // End of variables declaration//GEN-END:variables
}
